### ISSUE TITLE
Poll multiple jobs

### ISSUE THREAD

**Issue by pankajpatel** [alefragnani/vscode-jenkins-status#11]
Can it poll multiple Jobs as a project may have multiple jobs?

Similar to polling, this extension can be used to trigger the builds manually.
https://wiki.jenkins.io/display/jenkins/remote+access+api

**Comment by alefragnani** [comment]
Hi @pankajpatel ,

I think it should be splited in two diferente issues, so each one should be tracked separatedly 😄 

The first one (multiple jops), would require a bit more work, but some definitions are required:
* How each job _would be presented in the status bar_
* How the commands presented in the `Command Palette` would know/decide which job it is refering to
* How it would be handled in the `.jenkins` file, if you think about the _authentication_

The second (build command) is easier to do, based on the current model. I created #12 to track this.

What do you think about it?

**Comment by pankajpatel** [comment]
I can provide the suggestions in form of design and then explain about the flow. Will it be ok?

**Comment by alefragnani** [comment]
That's a good start 👍

**Comment by pankajpatel** [comment]
The `.jenkins` file can look like following:
```js
{
  "url": "http://127.0.0.1:8080/job/myproject",
  "username": "jenkins_user",
  "password": "jenkins_password_or_token",
  "jobs": {
    "jobName1": { //jobName1 can be shorter
      "name": "job-name-one" //can be same as jobName1
    }, 
    "jobName2": {
      "name": "job-name-one",
      "url": "http://127.0.0.1:8080/job/myproject", //->|
      "username": "jenkins_user",                   //->|---> custom config for the job
      "password": "jenkins_password_or_token"       //->|
    }
  }
}
```
![jobstatus-running](https://user-images.githubusercontent.com/251937/28117285-15894794-670d-11e7-9a66-a5e0a48f40fe.png)

![jobstatus-completed](https://user-images.githubusercontent.com/251937/28117292-1bdb4e76-670d-11e7-85d4-4d74bfaa2aaa.png)

![jobstatus-multiple](https://user-images.githubusercontent.com/251937/28117295-1ed484c6-670d-11e7-8970-d3e715af471f.png)

**Comment by alefragnani** [comment]
Hi @pankajpatel ,

First of all, thanks for your suggestion 👍 

I think the `.Jenkins` file would become simpler if it doesn't mix _single_ and the _multi-job_ configs. Maybe something like this:

```
{
    "jobs": [
        {
            "name": "First Job",
            "url": "http://127.0.0.1:8080/job/myproject",
        },
        {
            "name": "Second Job",
            "url": "http://127.0.0.1:8080/job/myOtherProject",
            "username": "jenkins_user",
            "password": "jenkins_password_or_token"
        }   
    ]   
}
```

About the StatusBar, I don't know if I understand the last image.  Are you suggesting to concatenate all jobs in the StatusBar? If yes, I think it would have an _alternate/compact_ idea, to avoid a StatusBar full of jobs (if there is a bunch of jobs, or if the jobName isn't short enough.

What do you think?

**Comment by pankajpatel** [comment]
Not all the jobs but the executing ones or the ones which have finished execution very shortly. And show ellipsis if the status text exceeds any specified length.

**Comment by alefragnani** [comment]
I guess that would be better if I just add to the StatusBar the jobs that _didn't have success_. Doing so, it's easy to see the jobs that needs attention.

**Comment by eramitmittal** [comment]
Have a look at https://github.com/eramitmittal/vscode-jenkins-status

**Comment by alefragnani** [comment]
I’m returning to the project, and the first step will be to merge the PR #17 from @eramitmittal . It should be released in the weekend. 

Stay tuned
