### ISSUE TITLE
The project is not enabled for Jenkins

### ISSUE THREAD

**Issue by i0natan** [alefragnani/vscode-jenkins-status#19]
Hi,

I configured everything by the book, have .jenkins file but when I try to run command via vscode I receive a notification about missing .jenkins file , see prtscn? any idea? 

My env: vscode 1.17.1 + win10

Thanks!

![image](https://user-images.githubusercontent.com/8571500/31606139-f9953c6e-b270-11e7-9100-3c5da039341b.png)

**Comment by eramitmittal** [comment]
You need to have the .jenkins file at the root level. Which means under 'API' folder in your code.

**Comment by i0natan** [comment]
oh, I knew that but didn't notice that I opened the project from the root's root :) thanks
