### ISSUE TITLE
Invalid URL error, possibly because my url has a space

### ISSUE THREAD

**Issue by tobiekruger** [alefragnani/vscode-jenkins-status#24]
My project name contains a space, and I keep getting invalid URL error, have also tried %20 instead of a space.

**Comment by alefragnani** [comment]
Hi @tobiekruger ,

I don't remember seeing this error, but I will look at it.

Do you have any additional log to show. What error message appears. You could try to use `Toggle Developer Tools / Console` and paste the info here.

Thanks

**Comment by tobiekruger** [comment]
Hi,

No info reported in that console, however, when I try the url in config without the "http://" i do get 2 "invalid protocol" errors in that console.

**Comment by alefragnani** [comment]
Hi @tobiekruger ,

Are you still having this issue? Have you managed to define a valid URL, so the extension could understand it and retrieve the correct job status?

Thank you

**Comment by alefragnani** [comment]
I'm closing this issue because no new comments has been made since my last question. 
Feel free to reopen/comment if the error still occurs.
