### ISSUE TITLE
Add possibility to keep .jenkins in .vscode project folder

### ISSUE THREAD

**Issue by r44083** [alefragnani/vscode-jenkins-status#28]
Since .vscode folder is common place to keep different settings related to project, it would be useful to keep .jenkins file into .vscode folder. More common way.

Could you please add this possibility? (for example check .vscode folder for .jenkins file firstly, after that check root of current project for .jenkins file).

**Comment by alefragnani** [comment]
Hi @r44083 ,

Yes, there is a similar request (#9). I will try to merge all ideas to handle both scenarios.

Hope this helps
