### ISSUE TITLE
Monitor job depending on git branch name

### ISSUE THREAD

**Issue by st-schneider** [alefragnani/vscode-jenkins-status#33]
It would be nice if the job would be dynamically picked by the current branch name for the status.

**Comment by alefragnani** [comment]
Hi @bm-stschneider ,

Could you elaborate/provide examples?

 I mean, the current monitoring is based on the _exact url_ defined in `.jenkins` file. There is no connection to folder name, workspace name or git repository name. To use the branch name, I think you are saying it would _replace/add_ pieces of that URL. Is that what you mean?

Thank you

**Comment by bm-stschneider** [comment]
Yes, there might not be a .jenkins file at all. But a common use case is to have jenkins build every branch on a repo for example. So lets say you have a repo `A` and someone pushes branch `feature/supercool-1`. Jenkins will create a job/project for that branch and build it immediately.
In this scenario it would be cool if there would be a status flag for the remote tracked branch of the current checked out branch to see if it fails on any part of the standard build process.

**Comment by LennyPenny** [comment]
I think #16 would solve this

**Comment by bm-stschneider** [comment]
In the meantime, we abandoned jenkins :P

**Comment by alefragnani** [comment]
Hi @bm-stschneider,

As I [commented here](https://github.com/alefragnani/vscode-jenkins-status/pull/17#issuecomment-587226210) I’m on similar situation. Most of our CI has moved to GitLab. That’s one of the reasons the extension is not being updated so frequently.

In [this comment](https://github.com/alefragnani/vscode-jenkins-status/pull/17#issuecomment-587417349) the PR author shows how you could use _dynamic imports_ to solve this, if anyone is interested, until this feature lands on newer releases. Or, as a start, for a new PR 😁 .

**Comment by alefragnani** [comment]
I'm closing this feature request because it didn’t receive enough upvotes from the community. Still a big Thank You to you for taking the time to create this issue!

Thanks for your understanding
