### ISSUE TITLE
Support Remote Development

### ISSUE THREAD

**Issue by alefragnani** [alefragnani/vscode-jenkins-status#41]
- [x] bump `vscode engine` version
- [x] `"extensionKind": ["ui", "workspace"]`
- [x] proper APIs (fs, open)
- [X] ~WebView API~
- [X] ~node APIs~

More info:
* https://code.visualstudio.com/blogs/2019/05/02/remote-development
* https://code.visualstudio.com/api/advanced-topics/remote-extensions

workspace.fs API available in VS Code 1.37 - July 2019
* https://code.visualstudio.com/updates/v1_37#_extension-authoring

**Comment by kalinkrustev** [comment]
This might help #76

**Comment by alefragnani** [comment]
The initial idea was to make the extension work both locally and remotely, but without the need to install it on the remote. For that, I could use the same approach used on my other extensions, removing access to file system via `fsPath` in favor of `Uri`.

It was possible to make it work, while loading `.jenkins` files (json), but not `.jenkinsrc.js` files (js).

Based on some testes, I've noticed that the snippet in #76 indeed work for `.jenkinsrc.js` files, both locally and remotely, but only if the extension installed on that remote. I couldn't make it work on remotes, with the extension installed locally.

So, for this particular scenario, when the workspace contains a `.jenkinsrc.js` file, the extension will work only if installed on the remote. If the user try to open a remote workspace with a `.jenkinsrc.js` file, a message will be displayed explaining the user: 

_**This workspace contains a `.jenkinsrc.js` file, which requires the Jenkins Status extension to be installed on the remote.**_

This tip will be added to the README file
