### ISSUE TITLE
[BUG] - open job url error

### ISSUE THREAD

**Issue by justforuse** [alefragnani/vscode-jenkins-status#87]
**Environment/version**

- Extension version: 4.4.1
- VSCode version: 1.71.2
- OS version: MacOS 12.5.1

**Steps to reproduce**

1. when execute `open job url`
2. Command 'Jenkins: Open in Browser' resulted in an error (command 'jenkins.openJobUrlToClipboard' not found)

my `.jenkins` file like: 
```
{
	"url": "https://jenkins.xxxx.com/path/of/project/my-project/",
    "username": "hello@world.com",
    "password" "token_from_jenkins"
}
```

**Comment by alefragnani** [comment]
Hi @justforuse ,

My **Jenkins Status** extension does not have those `Jenkins: Open in Browser` or `jenkins.openJobUrlToClipboard` commands, so I suppose you are using a different extension.

Name | Description | 
-- | -- | 
jenkins.updateStatus | Jenkins: Update Status |   
jenkins.openInJenkins | Jenkins: Open in Jenkins |   
jenkins.openInJenkinsConsoleOutput | Jenkins: Open in Jenkins (Console Output) |   
jenkins.whatsNew | Jenkins: What's New |   
jenkins._whatsNewContextMenu | What's New |  

I suggest you to double check which extension you are using. You probably have more than one installed, and this error comes from _the other_ extension.

Hope this helps

**Comment by justforuse** [comment]
thanks, I install two jenkins extensions😅
