### ISSUE TITLE
Remove unnecessary JenkinsIndicatorController class

### ISSUE THREAD

**Issue by md2perpe** [alefragnani/vscode-jenkins-status#96]
What is the meaning with the class `JenkinsIndicatorController` in JenkinsIndicator.ts? It seems to not do anything, not even collect things. The field `jenkinsIndicator` is set but never read, while the field `disposable` is read but never set.

**Comment by alefragnani** [comment]
Hi @md2perpe ,

Indeed, it is unnecessary today. It could be removed from the sources.

Did you noticed while building/debugging the extension?

**Comment by alefragnani** [comment]
A PR would be welcome, btw 😄

**Comment by md2perpe** [comment]
I noticed while reading and trying to understand the source.

**Comment by md2perpe** [comment]
Pull request #97 created.
